[package]
name = "program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan = "0.10.0"
obj-rs = "0.7"

[[bin]]
name = "program"
path = "main.rs"
